name: Update HMD Open Source Versions

on:
  schedule:
    - cron: '0 3 * * 2,5'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python scraper
        run: python scraper.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of HMD open source versions"
          file_pattern: "data/hmd_releases.json data/hmd_releases.sh"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"